import utils

WITCH_SPELLS = [
    "Acid Splash",
    "Blade Ward",
    "Chill Touch",
    "Control Flames",
    "Create Bonfire",
    "Dancing Lights",
    "Elementalism",
    "Friends",
    "Frostbite",
    "Guidance",
    "Gust",
    "Infestation",
    "Mage Hand",
    "Magic Stone",
    "Mending",
    "Message",
    "Mind Sliver",
    "Mold Earth",
    "Poison Spray",
    "Resistance",
    "Sapping Sting",
    "Shape Water",
    "Starry Wisp",
    "Thaumaturgy",
    "Thorn Whip",
    "Thunderclap",
    "True Strike",
    "Absorb Elements",
    "Alarm",
    "Animal Friendship",
    "Bane",
    "Beast Bond",
    "Cause Anguish",
    "Cause Fear",
    "Charm Person",
    "Concussive Jolt",
    "Create or Destroy Water",
    "Cure Wounds",
    "Detect Magic",
    "Detect Poison and Disease",
    "Earth Tremor",
    "Entangle",
    "Faerie Fire",
    "Feather Fall",
    "Fog Cloud",
    "Gift of Alacrity",
    "Goodberry",
    "Healing Word",
    "Jump",
    "Longstrider",
    "Protection from Evil and Good",
    "Purify Food and Drink",
    "Ray of Sickness",
    "Sanctuary",
    "Shadow Ray",
    "Sleep",
    "Speak with Animals",
    "Tasha's Caustic Brew",
    "Tasha's Hideous Laughter",
    "Unseen Servant",
    "Witch Bolt",
    "Aid",
    "Alter Self",
    "Animal Messenger",
    "Arcane Rend",
    "Augury",
    "Barkskin",
    "Beast Sense",
    "Blindness/Deafness",
    "Calm Emotions",
    "Darkvision",
    "Dust Devil",
    "Enhance Ability",
    "Enlarge/Reduce",
    "Enthrall",
    "Envenom",
    "Fortune's Favor",
    "Gust of Wind",
    "Healing Spirit",
    "Heat Metal",
    "Helpful Homunculi",
    "Hold Person",
    "Infirmity",
    "Lesser Restoration",
    "Locate Animals or Plants",
    "Magic Letter",
    "Magic Mouth",
    "Moonbeam",
    "Pass without Trace",
    "Protection from Poison",
    "Ray of Enfeeblement",
    "See Invisibility",
    "Silence",
    "Spike Growth",
    "Summon Beast",
    "Warding Wind",
    "Web",
    "Antagonize",
    "Bestow Curse",
    "Catnap",
    "Clairvoyance",
    "Conjure Animals",
    "Conjure Spirit Animals",
    "Create Food and Water",
    "Dispel Magic",
    "Enemies Abound",
    "Erupting Earth",
    "Fear",
    "Fortify",
    "Glyph of Warding",
    "Leomund's Tiny Hut",
    "Magic Circle",
    "Nondetection",
    "Plant Growth",
    "Protection from Energy",
    "Remove Curse",
    "Sending",
    "Speak with Dead",
    "Speak with Plants",
    "Summon Fey",
    "Summon Lesser Demons",
    "Tiny Servant",
    "Tongues",
    "Vampiric Touch",
    "Water Breathing",
    "Water Walk",
    "Wind Wall",
    "Backlash",
    "Banishment",
    "Blight",
    "Blood Curse",
    "Charm Monster",
    "Confusion",
    "Conjure Minor Elementals",
    "Conjure Nature Spirits",
    "Conjure Woodland Beings",
    "Divination",
    "Dominate Beast",
    "Doomtide",
    "Fount of Moonlight",
    "Freedom of Movement",
    "Giant Insect",
    "Grasping Vine",
    "Hallucinatory Terrain",
    "Locate Creature",
    "Mordenkainen's Faithful Hound",
    "Phantasmal Killer",
    "Polymorph",
    "Sickening Radiance",
    "Spectral Viper",
    "Stoneskin",
    "Summon Demon",
    "Summon Elemental",
    "Animate Objects",
    "Awaken",
    "Blindsense",
    "Circle of Power",
    "Commune with Nature",
    "Conjure Elemental",
    "Conjure Elemental Spirit",
    "Contact Other Plane",
    "Contagion",
    "Dispel Evil and Good",
    "Dominate Person",
    "Dream",
    "Enervation",
    "Greater Restoration",
    "Hold Monster",
    "Insect Plague",
    "Mass Cure Wounds",
    "Mislead",
    "Moon Bolt",
    "Moon Cloak",
    "Planar Binding",
    "Power Word Silence",
    "Reincarnate",
    "Scrying",
    "Seeming",
    "Skill Empowerment",
    "Transmute Rock",
    "Tree Stride",
    "Wrath of Nature",
    "Circle of Death",
    "Conjure Fey",
    "Create Homunculus",
    "Eyebite",
    "Find the Path",
    "Flesh to Stone",
    "Harm",
    "Heal",
    "Heroes' Feast",
    "Mental Prison",
    "Otto's Irresistible Dance",
    "Power Word Blind",
    "Programmed Illusion",
    "Scatter",
    "Soul Cage",
    "Summon Fiend",
    "Tasha's Bubbling Cauldron",
    "True Seeing",
    "Wall of Thorns",
    "Arcane Sight",
    "Arcane Siphon",
    "Crown of Stars",
    "Etherealness",
    "Finger of Death",
    "Mirage Arcane",
    "Moonfire",
    "Pale Knight's Portentous Premonition",
    "Plane Shift",
    "Power Word Fortify",
    "Power Word Pain",
    "Regenerate",
    "Symbol",
    "Tether Essence",
    "Voracious Poison",
    "Warding Whip",
    "Abi-Dalzim's Horrid Wilting",
    "Antipathy/Sympathy",
    "Control Weather",
    "Crippling Plague",
    "Discern Location",
    "Dominate Monster",
    "Feeblemind",
    "Lanathiil's Lucent Grove",
    "Maze",
    "Perinae's Plentiful Bounty",
    "Power Word Stun",
    "Astral Projection",
    "Foresight",
    "Imprisonment",
    "Mass Polymorph",
    "Moonfall",
    "Power Word Heal",
    "Power Word Kill",
    "Shapechange",
    "Time Ravage",
    "True Polymorph",
    "Virulent Doom",
    "Weird",
]

spells = utils.load_data("homebrew/ishiir-spells.json")

# Sanity Check
for spell in WITCH_SPELLS:
    if spell not in [s["name"] for s in spells["spell"]]:
        raise AssertionError(f"{spell} not found in source")

# Apply Changes
for spell in spells["spell"]:
    if spell["name"] in WITCH_SPELLS:
        if "Witch" not in [c["name"] for c in spell["classes"]["fromClassList"]]:
            spell["classes"]["fromClassList"].append({
                "name": "Witch",
                "source": "Ishiir"
            })

# Save Changes
utils.save_data(spells, "homebrew/ishiir-spells.json", True)
